export const RETURN_CODES = {
  SUCCESS: "SUCCESS",
  SERVER_ERROR: "SERVER_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_ALREADY_VERIFIED: "OTP_ALREADY_VERIFIED",
  OTP_INVALID: "OTP_INVALID",
  USER_DISABLED: "USER_DISABLED",
  USER_DELETED: "USER_DELETED",
  UNAUTHORIED: "UNAUTHORIED",
  STYLIST_ALREADY_REGISTERED: "STYLIST_ALREADY_REGISTERED",
};
